services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: sibuh
      POSTGRES_PASSWORD: sibuh
      POSTGRES_DB: projects
    volumes:
      - ./data:/var/lib/postgresql/data
      # - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - my-net
networks:
  my-net:
